/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkWithUsRouteImport } from './routes/work-with-us'
import { Route as StyleguideRouteImport } from './routes/styleguide'
import { Route as PrinciplesRouteImport } from './routes/principles'
import { Route as HowWeBuildRouteImport } from './routes/how-we-build'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkIndexRouteImport } from './routes/work/index'
import { Route as VenturesIndexRouteImport } from './routes/ventures/index'
import { Route as ThinkingIndexRouteImport } from './routes/thinking/index'
import { Route as WorkStudioExperimentsRouteImport } from './routes/work/studio-experiments'
import { Route as WorkClientSystemsRouteImport } from './routes/work/client-systems'
import { Route as VenturesCollectfastRouteImport } from './routes/ventures/collectfast'
import { Route as VenturesCasParserRouteImport } from './routes/ventures/cas-parser'
import { Route as VenturesBeonlyRouteImport } from './routes/ventures/beonly'
import { Route as ThinkingSystemsRouteImport } from './routes/thinking/systems'
import { Route as ThinkingLearningInPublicRouteImport } from './routes/thinking/learning-in-public'
import { Route as ThinkingExecutionRouteImport } from './routes/thinking/execution'
import { Route as ThinkingSlugRouteImport } from './routes/thinking/$slug'

const WorkWithUsRoute = WorkWithUsRouteImport.update({
  id: '/work-with-us',
  path: '/work-with-us',
  getParentRoute: () => rootRouteImport,
} as any)
const StyleguideRoute = StyleguideRouteImport.update({
  id: '/styleguide',
  path: '/styleguide',
  getParentRoute: () => rootRouteImport,
} as any)
const PrinciplesRoute = PrinciplesRouteImport.update({
  id: '/principles',
  path: '/principles',
  getParentRoute: () => rootRouteImport,
} as any)
const HowWeBuildRoute = HowWeBuildRouteImport.update({
  id: '/how-we-build',
  path: '/how-we-build',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkIndexRoute = WorkIndexRouteImport.update({
  id: '/work/',
  path: '/work/',
  getParentRoute: () => rootRouteImport,
} as any)
const VenturesIndexRoute = VenturesIndexRouteImport.update({
  id: '/ventures/',
  path: '/ventures/',
  getParentRoute: () => rootRouteImport,
} as any)
const ThinkingIndexRoute = ThinkingIndexRouteImport.update({
  id: '/thinking/',
  path: '/thinking/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkStudioExperimentsRoute = WorkStudioExperimentsRouteImport.update({
  id: '/work/studio-experiments',
  path: '/work/studio-experiments',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkClientSystemsRoute = WorkClientSystemsRouteImport.update({
  id: '/work/client-systems',
  path: '/work/client-systems',
  getParentRoute: () => rootRouteImport,
} as any)
const VenturesCollectfastRoute = VenturesCollectfastRouteImport.update({
  id: '/ventures/collectfast',
  path: '/ventures/collectfast',
  getParentRoute: () => rootRouteImport,
} as any)
const VenturesCasParserRoute = VenturesCasParserRouteImport.update({
  id: '/ventures/cas-parser',
  path: '/ventures/cas-parser',
  getParentRoute: () => rootRouteImport,
} as any)
const VenturesBeonlyRoute = VenturesBeonlyRouteImport.update({
  id: '/ventures/beonly',
  path: '/ventures/beonly',
  getParentRoute: () => rootRouteImport,
} as any)
const ThinkingSystemsRoute = ThinkingSystemsRouteImport.update({
  id: '/thinking/systems',
  path: '/thinking/systems',
  getParentRoute: () => rootRouteImport,
} as any)
const ThinkingLearningInPublicRoute =
  ThinkingLearningInPublicRouteImport.update({
    id: '/thinking/learning-in-public',
    path: '/thinking/learning-in-public',
    getParentRoute: () => rootRouteImport,
  } as any)
const ThinkingExecutionRoute = ThinkingExecutionRouteImport.update({
  id: '/thinking/execution',
  path: '/thinking/execution',
  getParentRoute: () => rootRouteImport,
} as any)
const ThinkingSlugRoute = ThinkingSlugRouteImport.update({
  id: '/thinking/$slug',
  path: '/thinking/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/how-we-build': typeof HowWeBuildRoute
  '/principles': typeof PrinciplesRoute
  '/styleguide': typeof StyleguideRoute
  '/work-with-us': typeof WorkWithUsRoute
  '/thinking/$slug': typeof ThinkingSlugRoute
  '/thinking/execution': typeof ThinkingExecutionRoute
  '/thinking/learning-in-public': typeof ThinkingLearningInPublicRoute
  '/thinking/systems': typeof ThinkingSystemsRoute
  '/ventures/beonly': typeof VenturesBeonlyRoute
  '/ventures/cas-parser': typeof VenturesCasParserRoute
  '/ventures/collectfast': typeof VenturesCollectfastRoute
  '/work/client-systems': typeof WorkClientSystemsRoute
  '/work/studio-experiments': typeof WorkStudioExperimentsRoute
  '/thinking/': typeof ThinkingIndexRoute
  '/ventures/': typeof VenturesIndexRoute
  '/work/': typeof WorkIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/how-we-build': typeof HowWeBuildRoute
  '/principles': typeof PrinciplesRoute
  '/styleguide': typeof StyleguideRoute
  '/work-with-us': typeof WorkWithUsRoute
  '/thinking/$slug': typeof ThinkingSlugRoute
  '/thinking/execution': typeof ThinkingExecutionRoute
  '/thinking/learning-in-public': typeof ThinkingLearningInPublicRoute
  '/thinking/systems': typeof ThinkingSystemsRoute
  '/ventures/beonly': typeof VenturesBeonlyRoute
  '/ventures/cas-parser': typeof VenturesCasParserRoute
  '/ventures/collectfast': typeof VenturesCollectfastRoute
  '/work/client-systems': typeof WorkClientSystemsRoute
  '/work/studio-experiments': typeof WorkStudioExperimentsRoute
  '/thinking': typeof ThinkingIndexRoute
  '/ventures': typeof VenturesIndexRoute
  '/work': typeof WorkIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/how-we-build': typeof HowWeBuildRoute
  '/principles': typeof PrinciplesRoute
  '/styleguide': typeof StyleguideRoute
  '/work-with-us': typeof WorkWithUsRoute
  '/thinking/$slug': typeof ThinkingSlugRoute
  '/thinking/execution': typeof ThinkingExecutionRoute
  '/thinking/learning-in-public': typeof ThinkingLearningInPublicRoute
  '/thinking/systems': typeof ThinkingSystemsRoute
  '/ventures/beonly': typeof VenturesBeonlyRoute
  '/ventures/cas-parser': typeof VenturesCasParserRoute
  '/ventures/collectfast': typeof VenturesCollectfastRoute
  '/work/client-systems': typeof WorkClientSystemsRoute
  '/work/studio-experiments': typeof WorkStudioExperimentsRoute
  '/thinking/': typeof ThinkingIndexRoute
  '/ventures/': typeof VenturesIndexRoute
  '/work/': typeof WorkIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/how-we-build'
    | '/principles'
    | '/styleguide'
    | '/work-with-us'
    | '/thinking/$slug'
    | '/thinking/execution'
    | '/thinking/learning-in-public'
    | '/thinking/systems'
    | '/ventures/beonly'
    | '/ventures/cas-parser'
    | '/ventures/collectfast'
    | '/work/client-systems'
    | '/work/studio-experiments'
    | '/thinking/'
    | '/ventures/'
    | '/work/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/how-we-build'
    | '/principles'
    | '/styleguide'
    | '/work-with-us'
    | '/thinking/$slug'
    | '/thinking/execution'
    | '/thinking/learning-in-public'
    | '/thinking/systems'
    | '/ventures/beonly'
    | '/ventures/cas-parser'
    | '/ventures/collectfast'
    | '/work/client-systems'
    | '/work/studio-experiments'
    | '/thinking'
    | '/ventures'
    | '/work'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/how-we-build'
    | '/principles'
    | '/styleguide'
    | '/work-with-us'
    | '/thinking/$slug'
    | '/thinking/execution'
    | '/thinking/learning-in-public'
    | '/thinking/systems'
    | '/ventures/beonly'
    | '/ventures/cas-parser'
    | '/ventures/collectfast'
    | '/work/client-systems'
    | '/work/studio-experiments'
    | '/thinking/'
    | '/ventures/'
    | '/work/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  HowWeBuildRoute: typeof HowWeBuildRoute
  PrinciplesRoute: typeof PrinciplesRoute
  StyleguideRoute: typeof StyleguideRoute
  WorkWithUsRoute: typeof WorkWithUsRoute
  ThinkingSlugRoute: typeof ThinkingSlugRoute
  ThinkingExecutionRoute: typeof ThinkingExecutionRoute
  ThinkingLearningInPublicRoute: typeof ThinkingLearningInPublicRoute
  ThinkingSystemsRoute: typeof ThinkingSystemsRoute
  VenturesBeonlyRoute: typeof VenturesBeonlyRoute
  VenturesCasParserRoute: typeof VenturesCasParserRoute
  VenturesCollectfastRoute: typeof VenturesCollectfastRoute
  WorkClientSystemsRoute: typeof WorkClientSystemsRoute
  WorkStudioExperimentsRoute: typeof WorkStudioExperimentsRoute
  ThinkingIndexRoute: typeof ThinkingIndexRoute
  VenturesIndexRoute: typeof VenturesIndexRoute
  WorkIndexRoute: typeof WorkIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/work-with-us': {
      id: '/work-with-us'
      path: '/work-with-us'
      fullPath: '/work-with-us'
      preLoaderRoute: typeof WorkWithUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/styleguide': {
      id: '/styleguide'
      path: '/styleguide'
      fullPath: '/styleguide'
      preLoaderRoute: typeof StyleguideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/principles': {
      id: '/principles'
      path: '/principles'
      fullPath: '/principles'
      preLoaderRoute: typeof PrinciplesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-we-build': {
      id: '/how-we-build'
      path: '/how-we-build'
      fullPath: '/how-we-build'
      preLoaderRoute: typeof HowWeBuildRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/': {
      id: '/work/'
      path: '/work'
      fullPath: '/work/'
      preLoaderRoute: typeof WorkIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ventures/': {
      id: '/ventures/'
      path: '/ventures'
      fullPath: '/ventures/'
      preLoaderRoute: typeof VenturesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/thinking/': {
      id: '/thinking/'
      path: '/thinking'
      fullPath: '/thinking/'
      preLoaderRoute: typeof ThinkingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/studio-experiments': {
      id: '/work/studio-experiments'
      path: '/work/studio-experiments'
      fullPath: '/work/studio-experiments'
      preLoaderRoute: typeof WorkStudioExperimentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/client-systems': {
      id: '/work/client-systems'
      path: '/work/client-systems'
      fullPath: '/work/client-systems'
      preLoaderRoute: typeof WorkClientSystemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ventures/collectfast': {
      id: '/ventures/collectfast'
      path: '/ventures/collectfast'
      fullPath: '/ventures/collectfast'
      preLoaderRoute: typeof VenturesCollectfastRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ventures/cas-parser': {
      id: '/ventures/cas-parser'
      path: '/ventures/cas-parser'
      fullPath: '/ventures/cas-parser'
      preLoaderRoute: typeof VenturesCasParserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ventures/beonly': {
      id: '/ventures/beonly'
      path: '/ventures/beonly'
      fullPath: '/ventures/beonly'
      preLoaderRoute: typeof VenturesBeonlyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/thinking/systems': {
      id: '/thinking/systems'
      path: '/thinking/systems'
      fullPath: '/thinking/systems'
      preLoaderRoute: typeof ThinkingSystemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/thinking/learning-in-public': {
      id: '/thinking/learning-in-public'
      path: '/thinking/learning-in-public'
      fullPath: '/thinking/learning-in-public'
      preLoaderRoute: typeof ThinkingLearningInPublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/thinking/execution': {
      id: '/thinking/execution'
      path: '/thinking/execution'
      fullPath: '/thinking/execution'
      preLoaderRoute: typeof ThinkingExecutionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/thinking/$slug': {
      id: '/thinking/$slug'
      path: '/thinking/$slug'
      fullPath: '/thinking/$slug'
      preLoaderRoute: typeof ThinkingSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  HowWeBuildRoute: HowWeBuildRoute,
  PrinciplesRoute: PrinciplesRoute,
  StyleguideRoute: StyleguideRoute,
  WorkWithUsRoute: WorkWithUsRoute,
  ThinkingSlugRoute: ThinkingSlugRoute,
  ThinkingExecutionRoute: ThinkingExecutionRoute,
  ThinkingLearningInPublicRoute: ThinkingLearningInPublicRoute,
  ThinkingSystemsRoute: ThinkingSystemsRoute,
  VenturesBeonlyRoute: VenturesBeonlyRoute,
  VenturesCasParserRoute: VenturesCasParserRoute,
  VenturesCollectfastRoute: VenturesCollectfastRoute,
  WorkClientSystemsRoute: WorkClientSystemsRoute,
  WorkStudioExperimentsRoute: WorkStudioExperimentsRoute,
  ThinkingIndexRoute: ThinkingIndexRoute,
  VenturesIndexRoute: VenturesIndexRoute,
  WorkIndexRoute: WorkIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
